export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SINGLE_REQUEST   = 'GET_SINGLE_REQUEST';
export const GET_SINGLE_FAILURE   = 'GET_SINGLE_FAILURE';
export const GET_SINGLE_SUCCESS   = 'GET_SINGLE_SUCCESS';